#pragma once
// Autogenerated icons
#include <tasks_icons.h>
#include <string>
#include <cstring>
#include "../UFZ/UI.hpp"

#define CTX(x) ((FTasks::ApplicationData*)(x))
#define TASKS_TODO_DATA_FILE STORAGE_APP_DATA_PATH_PREFIX"/todo.save"
#define TASKS_DONE_DATA_FILE STORAGE_APP_DATA_PATH_PREFIX"/done.save"

namespace FTasks
{
    inline constexpr const char* newLine = "\n";

    namespace Scenes
    {
        enum Scenes
        {
            MAIN_MENU,
            EDIT_MENU,
            NAME_TEXT_EDIT,
            DESCRIPTION_TEXT_EDIT,
            DESCRIPTION,
            DELETE,
            POPUP,
        };
    }

    // Main menu items are submitted as custom events carrying a note index. Offsetting them past the last scene value
    // keeps them from colliding with the scene ids that are also sent as custom events. Scenes::POPUP is not a real
    // scene, it only marks the first free value, so keep it last in the enum above.
    inline constexpr uint32_t noteEventOffset = Scenes::POPUP;

    namespace Dialogs
    {
        enum Dialogs
        {
            DESCRIPTION,
            DONE,
            RENAME,
            EDIT_DESCRIPTION,
            DELETE
        };
    }


    typedef std::vector<std::pair<std::string, std::string>> NoteContainer;

    struct Containers
    {
        NoteContainer todo{ { "+ New task", "Describes a new task" } };
        NoteContainer done{};
    };

    struct ApplicationData
    {
        std::string tmpBuffer;

        std::string inputTextBuffer;

        Containers containers{};

        NoteContainer* currentContainer = &containers.todo;
        size_t currentNoteIndex = 0;

        bool bMakingNewNote = false;

        // Set when returning to the main menu should re-select currentNoteIndex. Only non-destructive edits set this;
        // deleting a task or marking it as (not) done invalidates the index, so those reset the selection to the top.
        bool bPreserveSelection = false;
    };

    namespace Data
    {
        void writeContainerString(const NoteContainer& container, const UFZ::File& file) noexcept;
        void readContainerString(NoteContainer& container, const UFZ::File& file) noexcept;

        void save(const UFZ::Application& application) noexcept;
        void load(const UFZ::Application& application) noexcept;
    }
}