#pragma once
// Autogenerated icons
#include <tasks_icons.h>
#include <string>
#include <cstring>
#include "../UFZ/UI.hpp"

#define CTX(x) ((FTasks::ApplicationData*)(x))
// The note the user currently has selected, i.e. what currentContainer/currentNoteIndex point at
#define CURRENT_NOTE(x) ((*(x)->currentContainer)[(x)->currentNoteIndex])
#define TASKS_TODO_DATA_FILE STORAGE_APP_DATA_PATH_PREFIX"/todo.save"
#define TASKS_DONE_DATA_FILE STORAGE_APP_DATA_PATH_PREFIX"/done.save"

namespace FTasks
{
    inline constexpr const char* newLine = "\n";

    namespace Scenes
    {
        enum Scenes
        {
            MAIN_MENU,
            EDIT_MENU,
            NAME_TEXT_EDIT,
            DESCRIPTION_TEXT_EDIT,
            DESCRIPTION,
            DELETE,
            POPUP,
        };
    }

    // Main menu items are submitted as custom events carrying a note index. Offsetting them past the last scene value
    // keeps them from colliding with the scene ids that are also sent as custom events. Scenes::POPUP is not a real
    // scene, it only marks the first free value, so keep it last in the enum above.
    inline constexpr uint32_t noteEventOffset = Scenes::POPUP;

    namespace Dialogs
    {
        enum Dialogs
        {
            DESCRIPTION,
            DONE,
            RENAME,
            EDIT_DESCRIPTION,
            DELETE
        };
    }


    typedef std::vector<std::pair<std::string, std::string>> NoteContainer;

    // The first todo entry is a sentinel: selecting index 0 creates a new task (List::event). It belongs to the
    // code, not the save file — Data::save omits it and Data::load re-inserts it — so it exists exactly once no
    // matter what the persisted file holds. Older builds stored it in todo.save; Data::load strips that copy on
    // the way in. Seed, save-skip and load migration all key off these two strings, so keep them the single source.
    inline constexpr const char* newTaskName = "+ New task";
    inline constexpr const char* newTaskDescription = "Describes a new task";

    struct Containers
    {
        NoteContainer todo{ { newTaskName, newTaskDescription } };
        NoteContainer done{};
    };

    struct ApplicationData
    {
        // Scratch text displayed by widgets. DialogEx and Popup store the raw pointer they are given (only
        // Submenu copies its header), so whatever scene hands tmpBuffer to such a widget owns it until that
        // scene exits — nothing else may write tmpBuffer while the widget is still on screen. Sharing it
        // between the EDIT_MENU header and the delete dialog text works only because the header is copied
        std::string tmpBuffer;

        std::string inputTextBuffer;

        Containers containers{};

        NoteContainer* currentContainer = &containers.todo;
        size_t currentNoteIndex = 0;

        bool bMakingNewNote = false;

        // Set when returning to the main menu should re-select currentNoteIndex. Only non-destructive edits set this;
        // deleting a task or marking it as (not) done invalidates the index, so those reset the selection to the top.
        bool bPreserveSelection = false;
    };

    namespace Data
    {
        void writeContainerString(const NoteContainer& container, const UFZ::File& file, size_t start = 0) noexcept;
        void readContainerString(NoteContainer& container, const UFZ::File& file) noexcept;

        void save(const UFZ::Application& application) noexcept;
        void load(const UFZ::Application& application) noexcept;
    }
}