#pragma once
// Autogenerated icons
#include <tasks_icons.h>
#include <string>
#include "../UFZ/UI.hpp"

#define CTX(x) ((FTasks::ApplicationData*)(x))
#define TASKS_TODO_DATA_FILE STORAGE_APP_DATA_PATH_PREFIX"/todo.save"
#define TASKS_DONE_DATA_FILE STORAGE_APP_DATA_PATH_PREFIX"/done.save"

namespace FTasks
{
    inline constexpr const char* newLine = "\n";

    namespace Scenes
    {
        enum Scenes
        {
            MAIN_MENU,
            EDIT_MENU,
            NAME_TEXT_EDIT,
            DESCRIPTION_TEXT_EDIT,
            DESCRIPTION,
            DELETE,
            POPUP,
        };
    }

    namespace Dialogs
    {
        enum Dialogs
        {
            DESCRIPTION,
            DONE,
            RENAME,
            EDIT_DESCRIPTION,
            DELETE
        };
    }


    typedef std::vector<std::pair<std::string, std::string>> NoteContainer;

    struct Containers
    {
        NoteContainer todo{ { "+ New task", "Describes a new task" } };
        NoteContainer done{};
    };

    struct ApplicationData
    {
        std::string tmpBuffer;

        std::string dialogTextStorage;
        std::string inputTextBuffer;

        Containers containers{};

        NoteContainer* currentContainer = &containers.todo;
        size_t currentNoteIndex = 0;

        bool bMakingNewNote = false;
    };

    namespace Data
    {
        void writeContainerString(const NoteContainer& container, UFZ::File& file) noexcept;
        void readContainerString(NoteContainer& container, UFZ::File& file) noexcept;

        void save(UFZ::Application& application) noexcept;
        void load(UFZ::Application& application) noexcept;
    }
}